dbt_core_databricks:
  outputs:
    dev:
      catalog: "{{ env_var('DATABRICKS_CATALOG_DEV') }}"
      host: "{{ env_var('DATABRICKS_HOST_DEV') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH_DEV') }}"
      schema: default
      threads: 1
      token: "{{ env_var('DATABRICKS_TOKEN_DEV') }}"
      type: databricks
    prod:
      catalog: "{{ env_var('DATABRICKS_CATALOG_PROD') }}"
      host: "{{ env_var('DATABRICKS_HOST_PROD') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH_PROD') }}"
      schema: default
      threads: 1
      token: "{{ env_var('DATABRICKS_TOKEN_PROD') }}"
      type: databricks
  target: dev