
snapshots:
  - name: products_snapshot
    relation: source('landing', 'products')
    config:
      schema: bronze
      database: dbt_project_catalog
      unique_key: id
      strategy: timestamp
      updated_at: created_at
      #dbt_valid_to_current: "to_date('9999-12-31')"